language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

addons:
  chrome: stable

env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint
  - go get github.com/spatialmodel/inmap/cmd/inmap

install:
- go get github.com/agnivade/wasmbrowsertest
- mv $GOPATH/bin/wasmbrowsertest $GOPATH/bin/go_js_wasm_exec
- export PATH=$GOPATH/bin:$PATH

script:
  - go test -v
  - GOOS=js GOARCH=wasm go test -v ./gui
